language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
env:
  global:
    secure: oNpak7eyZszipBMtkVKFmiAv7k5WSkz3WVKlDVCS3m2TXeFGGO4Dm+unrBKBXZtTwCfO4n65o+xx89rlCHG1JdFNEiSmd+y9ROXOOx17jJnWSEz4+Tfjc/DRWOa7agPLSsTbezsCHSxia2BRoUVTQFLdan9PrMXQW2HTmwVgSO1GEgBSVn3Jdd97Rpx4ulJCJ7vc+Ds9PvHfBGtNILnlW2cBWhdwC9fBEMblTLGK7rhIViYHao9sj8JGHG1Ql02YxB77Ond/xvBobEwrrPqlZRL3hn1mbPY4bEavYrakamfG8OFZNAhnDEoN4YTC0IifZIbHRt7omPPX0qUNVbzRwq+LHGbLbGvSC/rRiYPjTc5Gyd20lQTlp0pHj4rsAFERXJuzp9nkd/H4AAX/Fw6pUcJBJrlhIxvnIotbJtot5vI+wQGg9ZGyjZGQQEf6XSblR2Y4Cte/UIuCTJqj/NWtFgpGVjf4CFH0L7+NAeeDLqM3YVdxUSw1CvvQIZVcW1VFkSlv6NPPknmL7F26ajZkzDu8XKEHLfVmpFCNY9ixhmXWt1PFrCRU6SyyJaUzaGmmTZ92u9Kvxz+rFt8mqJ0lw7oJgMPgr6FFS8IdN3zDVn7mEHIYMWaK7AtTjf7186qh06yu2HUmIQqS4uBvma5BGiDMQHMLAx+i2M+GvstNLIo=
addons:
  sonarqube: true
script:
  - sbt clean coverage scalastyle test
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
after_success: sbt coverageReport coveralls
